// Code generated by protoc-gen-go. DO NOT EDIT.
// source: AgentService.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	AgentService.proto

It has these top-level messages:
	CoordinatorCaptureRequest
	AgentCaptureResponse
	CoordinatorGoodByeRequest
	AgentGoodByeResponse
	CoordinatorResultsRequest
	AgentResultsResponse
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CoordinatorCaptureRequest struct {
}

func (m *CoordinatorCaptureRequest) Reset()                    { *m = CoordinatorCaptureRequest{} }
func (m *CoordinatorCaptureRequest) String() string            { return proto.CompactTextString(m) }
func (*CoordinatorCaptureRequest) ProtoMessage()               {}
func (*CoordinatorCaptureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AgentCaptureResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *AgentCaptureResponse) Reset()                    { *m = AgentCaptureResponse{} }
func (m *AgentCaptureResponse) String() string            { return proto.CompactTextString(m) }
func (*AgentCaptureResponse) ProtoMessage()               {}
func (*AgentCaptureResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AgentCaptureResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CoordinatorGoodByeRequest struct {
}

func (m *CoordinatorGoodByeRequest) Reset()                    { *m = CoordinatorGoodByeRequest{} }
func (m *CoordinatorGoodByeRequest) String() string            { return proto.CompactTextString(m) }
func (*CoordinatorGoodByeRequest) ProtoMessage()               {}
func (*CoordinatorGoodByeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type AgentGoodByeResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *AgentGoodByeResponse) Reset()                    { *m = AgentGoodByeResponse{} }
func (m *AgentGoodByeResponse) String() string            { return proto.CompactTextString(m) }
func (*AgentGoodByeResponse) ProtoMessage()               {}
func (*AgentGoodByeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AgentGoodByeResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CoordinatorResultsRequest struct {
}

func (m *CoordinatorResultsRequest) Reset()                    { *m = CoordinatorResultsRequest{} }
func (m *CoordinatorResultsRequest) String() string            { return proto.CompactTextString(m) }
func (*CoordinatorResultsRequest) ProtoMessage()               {}
func (*CoordinatorResultsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type AgentResultsResponse struct {
	Status     string                                       `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	CaptureMap map[string]*AgentResultsResponse_CaptureInfo `protobuf:"bytes,2,rep,name=captureMap" json:"captureMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AgentResultsResponse) Reset()                    { *m = AgentResultsResponse{} }
func (m *AgentResultsResponse) String() string            { return proto.CompactTextString(m) }
func (*AgentResultsResponse) ProtoMessage()               {}
func (*AgentResultsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AgentResultsResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AgentResultsResponse) GetCaptureMap() map[string]*AgentResultsResponse_CaptureInfo {
	if m != nil {
		return m.CaptureMap
	}
	return nil
}

type AgentResultsResponse_CaptureInfo struct {
	Oplatency string `protobuf:"bytes,1,opt,name=oplatency" json:"oplatency,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Opaque    string `protobuf:"bytes,3,opt,name=opaque" json:"opaque,omitempty"`
}

func (m *AgentResultsResponse_CaptureInfo) Reset()         { *m = AgentResultsResponse_CaptureInfo{} }
func (m *AgentResultsResponse_CaptureInfo) String() string { return proto.CompactTextString(m) }
func (*AgentResultsResponse_CaptureInfo) ProtoMessage()    {}
func (*AgentResultsResponse_CaptureInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

func (m *AgentResultsResponse_CaptureInfo) GetOplatency() string {
	if m != nil {
		return m.Oplatency
	}
	return ""
}

func (m *AgentResultsResponse_CaptureInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AgentResultsResponse_CaptureInfo) GetOpaque() string {
	if m != nil {
		return m.Opaque
	}
	return ""
}

func init() {
	proto.RegisterType((*CoordinatorCaptureRequest)(nil), "rpc.CoordinatorCaptureRequest")
	proto.RegisterType((*AgentCaptureResponse)(nil), "rpc.AgentCaptureResponse")
	proto.RegisterType((*CoordinatorGoodByeRequest)(nil), "rpc.CoordinatorGoodByeRequest")
	proto.RegisterType((*AgentGoodByeResponse)(nil), "rpc.AgentGoodByeResponse")
	proto.RegisterType((*CoordinatorResultsRequest)(nil), "rpc.CoordinatorResultsRequest")
	proto.RegisterType((*AgentResultsResponse)(nil), "rpc.AgentResultsResponse")
	proto.RegisterType((*AgentResultsResponse_CaptureInfo)(nil), "rpc.AgentResultsResponse.CaptureInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AgentService service

type AgentServiceClient interface {
	CaptureSignal(ctx context.Context, in *CoordinatorCaptureRequest, opts ...grpc.CallOption) (*AgentCaptureResponse, error)
	GoodByeSignal(ctx context.Context, in *CoordinatorGoodByeRequest, opts ...grpc.CallOption) (*AgentGoodByeResponse, error)
	AgentResults(ctx context.Context, in *CoordinatorResultsRequest, opts ...grpc.CallOption) (*AgentResultsResponse, error)
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) CaptureSignal(ctx context.Context, in *CoordinatorCaptureRequest, opts ...grpc.CallOption) (*AgentCaptureResponse, error) {
	out := new(AgentCaptureResponse)
	err := grpc.Invoke(ctx, "/rpc.AgentService/CaptureSignal", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GoodByeSignal(ctx context.Context, in *CoordinatorGoodByeRequest, opts ...grpc.CallOption) (*AgentGoodByeResponse, error) {
	out := new(AgentGoodByeResponse)
	err := grpc.Invoke(ctx, "/rpc.AgentService/GoodByeSignal", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AgentResults(ctx context.Context, in *CoordinatorResultsRequest, opts ...grpc.CallOption) (*AgentResultsResponse, error) {
	out := new(AgentResultsResponse)
	err := grpc.Invoke(ctx, "/rpc.AgentService/AgentResults", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgentService service

type AgentServiceServer interface {
	CaptureSignal(context.Context, *CoordinatorCaptureRequest) (*AgentCaptureResponse, error)
	GoodByeSignal(context.Context, *CoordinatorGoodByeRequest) (*AgentGoodByeResponse, error)
	AgentResults(context.Context, *CoordinatorResultsRequest) (*AgentResultsResponse, error)
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_CaptureSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CaptureSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AgentService/CaptureSignal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CaptureSignal(ctx, req.(*CoordinatorCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GoodByeSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorGoodByeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GoodByeSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AgentService/GoodByeSignal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GoodByeSignal(ctx, req.(*CoordinatorGoodByeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AgentResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AgentResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AgentService/AgentResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AgentResults(ctx, req.(*CoordinatorResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CaptureSignal",
			Handler:    _AgentService_CaptureSignal_Handler,
		},
		{
			MethodName: "GoodByeSignal",
			Handler:    _AgentService_GoodByeSignal_Handler,
		},
		{
			MethodName: "AgentResults",
			Handler:    _AgentService_AgentResults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AgentService.proto",
}

func init() { proto.RegisterFile("AgentService.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x9b, 0x04, 0x0b, 0xbd, 0x55, 0x94, 0x41, 0x24, 0xad, 0x22, 0x25, 0x20, 0xd4, 0x4d,
	0x16, 0x75, 0x23, 0xba, 0xd2, 0x22, 0x52, 0xd4, 0x4d, 0x8a, 0x0f, 0x30, 0xa6, 0xd7, 0x52, 0x0c,
	0x33, 0xd3, 0xf9, 0x29, 0xe4, 0xc5, 0x7c, 0x35, 0xb7, 0x92, 0x64, 0x9a, 0xa4, 0xa9, 0x55, 0xdc,
	0x65, 0x4e, 0xe6, 0x7c, 0xf7, 0xdc, 0xe4, 0x00, 0xb9, 0x9b, 0x23, 0xd3, 0x53, 0x94, 0xab, 0x45,
	0x8c, 0xa1, 0x90, 0x5c, 0x73, 0xe2, 0x49, 0x11, 0x07, 0xa7, 0xd0, 0x1b, 0x73, 0x2e, 0x67, 0x0b,
	0x46, 0x35, 0x97, 0x63, 0x2a, 0xb4, 0x91, 0x18, 0xe1, 0xd2, 0xa0, 0xd2, 0x41, 0x08, 0xc7, 0xb9,
	0xaf, 0x94, 0x95, 0xe0, 0x4c, 0x21, 0x39, 0x81, 0xb6, 0xd2, 0x54, 0x1b, 0xe5, 0x3b, 0x03, 0x67,
	0xd8, 0x89, 0xec, 0xa9, 0x01, 0x7b, 0xe4, 0x7c, 0x76, 0x9f, 0x6e, 0xc1, 0x4a, 0xf9, 0x5f, 0xb0,
	0x08, 0x95, 0x49, 0xb4, 0x5a, 0xc3, 0x3e, 0x5d, 0x4b, 0x2b, 0xf5, 0xdf, 0x69, 0x64, 0x02, 0x10,
	0x17, 0x5b, 0xbc, 0x50, 0xe1, 0xbb, 0x03, 0x6f, 0xd8, 0x1d, 0x5d, 0x86, 0x52, 0xc4, 0xe1, 0x4f,
	0x98, 0x70, 0x5c, 0xde, 0x7d, 0x60, 0x5a, 0xa6, 0x51, 0xcd, 0xdc, 0x7f, 0x85, 0xae, 0x7d, 0x3d,
	0x61, 0xef, 0x9c, 0x9c, 0x41, 0x87, 0x8b, 0x84, 0x6a, 0x64, 0x71, 0x6a, 0x87, 0x56, 0x02, 0x39,
	0x02, 0xef, 0x03, 0x53, 0xdf, 0xcd, 0xf5, 0xec, 0x31, 0x4b, 0xc8, 0x05, 0x5d, 0x1a, 0xf4, 0xbd,
	0x22, 0x61, 0x71, 0xea, 0xcf, 0xe0, 0xb0, 0x31, 0x75, 0x6d, 0x76, 0x2a, 0xf3, 0x2d, 0xec, 0xad,
	0x68, 0x62, 0x30, 0x07, 0x76, 0x47, 0x17, 0x7f, 0x6e, 0x90, 0x45, 0x8c, 0x0a, 0xcf, 0x8d, 0x7b,
	0xed, 0x8c, 0xbe, 0x1c, 0xd8, 0xaf, 0x77, 0x81, 0x3c, 0xc3, 0x81, 0xbd, 0x3a, 0x5d, 0xcc, 0x19,
	0x4d, 0xc8, 0x79, 0xce, 0xdc, 0x59, 0x8a, 0x7e, 0xaf, 0x9a, 0xd9, 0xe8, 0x45, 0xd0, 0xca, 0x68,
	0xf6, 0xff, 0xee, 0xa2, 0x6d, 0xb6, 0xa2, 0x4e, 0x6b, 0x14, 0x23, 0x68, 0x91, 0x27, 0x9b, 0xd5,
	0xee, 0xb6, 0x0d, 0xdb, 0x6c, 0x45, 0x1d, 0xd6, 0xf8, 0x1c, 0x41, 0xeb, 0xad, 0x9d, 0xb7, 0xfe,
	0xea, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x09, 0x2c, 0x60, 0x0b, 0x03, 0x00, 0x00,
}
